### ISSUE TITLE
Fails to install on python 2.6

### ISSUE THREAD

**Issue by mkumatag** [kontron/python-ipmi#11]
While installing through pip in Python 2.6 got following error message:

(jjb_env)[manjunath@oc1275007250 ~]$ pip install python-ipmi
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting python-ipmi
/home/manjunath/jjb_env/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading python-ipmi-0.1.2.tar.gz (54kB)
    100% |████████████████████████████████| 57kB 228kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-2L4i46/python-ipmi/setup.py", line 11, in <module>
        version = subprocess.check_output(
    AttributeError: 'module' object has no attribute 'check_output'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2L4i46/python-ipmi

Should give me proper message saying not supported on 2.6.! should block installing on python 2.6 if not supported.

**Comment by hthiery** [comment]
We only support python 2.7

**Comment by mkumatag** [comment]
if that is the case, why are we even packaging for 2.6?

**Comment by hthiery** [comment]
OK. I'm not realy sure. Do you know how to enable and fix this?
