### ISSUE TITLE
unsupported format string

### ISSUE THREAD

**Issue by hinxx** [kontron/python-ipmi#119]
When hitting this line of code:

https://github.com/kontron/python-ipmi/blob/2961fca93bdd6576f99ddffdc793720070795d09/pyipmi/ipmitool.py#L208

I get the error `TypeError: unsupported format string passed to bytes.__format__`.

Changing the line to `s.device_id_string.decode('utf-8'),` makes the error go away for me.

**Comment by hinxx** [comment]
Just noticed this is a duplicate of #90 .

**Comment by hthiery** [comment]
could you provide a raw SDR dump of the failed record?
