### ISSUE TITLE
GetChassisStatusRsp did not handle optional byte in response data

### ISSUE THREAD

**Issue by hustbeta** [kontron/python-ipmi#13]
From the ipmi 2.0 spec, 28.2 Get Chassis Status Command, there is an optional extra byte in response data. So the response could be 5 bytes. But **GetChassisStatusRsp** handles 4 bytes only, which will raise DecodingError('Data has extra bytes'). I have came across this problem on some HP servers, they returned the optional byte as 0x00.

I am not familiar with the source code, maybe appending a **RemainingBytes** to **GetChassisStatusRsp** will solve the issue?

**Comment by hthiery** [comment]
indeed this extra bytes is not handled.

**Comment by hthiery** [comment]
It is fixed by adding "optional" field.
