### ISSUE TITLE
Migrate nose testing framework to other testing frameworks

### ISSUE THREAD

**Issue by tai271828** [kontron/python-ipmi#133]
nose is an inactive project and the latest release is 7 years ago (2015, version 1.3.7). It will be great if the testing framework could migrate to the other testing frameworks that are still active.

FWIW:
- The migration will also help distributions evolve, e.g. [Debian Bug report #1018466](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018466).
- There is a script called [nose2pytest](https://github.com/pytest-dev/nose2pytest) which can assist with migrating from nose to pytest.

**Comment by hthiery** [comment]
Hi, from where this need comes?  We use nose2 where the last release is from this year [1].

[1] https://docs.nose2.io/en/latest/changelog.html#id1

**Comment by hthiery** [comment]
We switched to pytest. So I will close this issue.
