### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Teslafly** [kontron/python-ipmi#14]
I have been working on making this work with python 3, and I believe I have been successful.
I have all tests passing, and the example in the readme + a few other variations have identical behavior in both python 2 & 3.
You can find the fork here [https://github.com/Teslafly/python-ipmi](https://github.com/Teslafly/python-ipmi)
The thing is, this was fairly quick and dirty, (futureise & 2to3 + i/o fixes) and I have alternative (aka, custom) hardware / uses for this library, so am not able to test most interfaces / functionality.

If this can be tested, or reviewed in any way to make sure it actually works in the intended circumstances, that would be preferable to do before a pull.

**Comment by hthiery** [comment]
I will take a look on it and check it with the others Interfaces. Did you only check with the custom One?

**Comment by Teslafly** [comment]
I only checked it (aka, used it at all except for existing unittests) with the custom interface, yes.

Basic commands such as 'get_device_id()' do seem to work though.

**Comment by Teslafly** [comment]
I only checked it (aka, used it at all except for existing unittests) with the custom interface, yes.

Basic commands such as 'get_device_id()' do seem to work though.

get_device_sdr_list() seems to be having some recursion / infinite inheritance issues though now that I've actually tested that.

**Comment by Teslafly** [comment]
I fixed the recursion error and tested just about everything my board supports (mostly fru and sdr). It all seems to work.

**Comment by hthiery** [comment]
Unfortunately I had not the time to work on it. But I did a quick check and
tried to run the ipmitool.py but it ends with some errors. Maybe you can
try that tool too.
Am 01.06.2016 19:36 schrieb "Teslafly" <notifications@github.com>:

**Comment by Teslafly** [comment]
my latest commit should fix the ipmitool bug. It also adds support for ipmitool's 'serial-terminal' interface. (which I have tested successfully)
I do not have the ability to test the lan modes, but believe the bug you were running into is fixed.

**Comment by hthiery** [comment]
I checked your fork against our setups and it seems to still work with python 2.7. unfortunatly i cannot test again python 3 because there are also other modules invoked in our setup that doesnt support python 3.

So I'm interested in merging it back to the master branch. can you prepare a pull request or do you plan to do more work on it?

**Comment by Teslafly** [comment]
I think I'm pretty much done with work on it.
As for python 3 support, it seems to be working well, at least with general functions, sdr's and fru/s.  so it is working fine with python 3.4 and 3.5 in our setups.

I'll put together a pull request.

**Comment by hthiery** [comment]
Sounds good.
Am 13.06.2016 22:17 schrieb "Teslafly" <notifications@github.com>:

**Comment by hthiery** [comment]
Python 3 merged.
