### ISSUE TITLE
Useless dependency of future

### ISSUE THREAD

**Issue by frenzymadness** [kontron/python-ipmi#158]
Hello. I see that the project depends on future but I cannot find a single usage of it in the codebase.
https://github.com/kontron/python-ipmi/blob/8e83f6f1de1c774cc9bdce90955b9917674351d4/setup.py#L76-L78
Do you think it's still useful? I'm asking because future is broken with the latest Python 3.12 and will be even more with 3.13 so it might be a good idea to get rid of it.

**Comment by hthiery** [comment]
will be fixed by https://github.com/kontron/python-ipmi/pull/163

**Comment by frenzymadness** [comment]
PR #163 has been merged.
