### ISSUE TITLE
send_message method can loop forever

### ISSUE THREAD

**Issue by BenEstrabaud** [kontron/python-ipmi#25]
Hi,

In the following code block:
   
```
 def send_message(self, req):
        req.target = self.target
        req.requester = self.requester

        retry = 3
        while True:
            retry -= 1
            try:
                rsp = self.interface.send_and_receive(req)
                break
            except CompletionCodeError as e:
                if e.cc == msgs.constants.CC_NODE_BUSY:
                    retry -= 1
                    continue

        return rsp

```
The "retry" variable is actually never checked. Also, If we get a CompletionCodeError when trying to call self.interface.send_and_receive, we substract one to the retry again even though we've only done a single attempt (but substracted 2 to the retry). If we consistently fail to complete the command, the while loop will never exit. Finally, "rsp" isn't initialized and the "continue" statement at the end of the code block is unecessary: the next line would automatically go to the next iteration of the while loop.

This can probably be fixed with something like that (not tested):

```
 def send_message(self, req):
        req.target = self.target
        req.requester = self.requester
        rsp = None
        retry = 3
        while retry > 0:
            retry -= 1
            try:
                rsp = self.interface.send_and_receive(req)
                break
            except CompletionCodeError as e:
                pass
        return rsp
```

**Comment by hthiery** [comment]
thats is right .. do you have the chance to test your changes?

**Comment by BenEstrabaud** [comment]
Hi,

I don't have access to an IPMI enabled machine right now, so it's a bit awkward for me to test those changes. If I get a chance to I will.
