### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by msabramo** [kontron/python-ipmi#3]
It's registered on PyPI but nothing has been uploaded. 

https://pypi.python.org/pypi/python-ipmi/0.1

**Comment by mwalle** [comment]
yeah this is just a placeholder for now, we have to change the projects name to python-ipmi. pyipmi is already taken. maybe i'll find some time this week.

**Comment by hthiery** [comment]
version 0.1.0 is now available under https://pypi.python.org/pypi/python-ipmi/0.1.0
