### ISSUE TITLE
throw a error when I try to connect the ipmi host 

### ISSUE THREAD

**Issue by CengSin** [kontron/python-ipmi#35]
![image](https://user-images.githubusercontent.com/23357893/46128994-e4274900-c267-11e8-8dd2-a14ae8e417cb.png)

I don't know how to get the IPMB, so,  I use another issue code 

```python
interface = pyipmi.interfaces.create_interface('ipmitool', interface_type='lanplus')

    connection = pyipmi.create_connection(interface)

    connection.target = pyipmi.Target(0x20)
    connection.target.set_routing([(0x20, 0)])

    connection.session.set_session_type_rmcp(host_name, port=22)
    connection.session.set_auth_type_user(user, password)
    connection.session.establish()

    connection.get_chassis_status()
```

**Comment by CengSin** [comment]
the error is `RuntimeError: ipmitool failed with rc=2`

**Comment by hthiery** [comment]
What physical connection so you use?

**Comment by hthiery** [comment]
Please increase the lib Log Level to debug to see the used ipmitool command

**Comment by CengSin** [comment]
how to set the lib Log Level

**Comment by hthiery** [comment]
`
handler = logging.StreamHandler()

if verbose:
        handler.setLevel(logging.DEBUG)

else:
        handler.setLevel(logging.INFO)
pyipmi.logger.add_log_handler(handler)
pyipmi.logger.set_log_level(logging.DEBUG)
`

**Comment by CengSin** [comment]
```python
Running ipmitool "ipmitool -I lanplus -H 172.16.19.111 -p 22 -U "root" -P "calvin" -b 0 -t 0x20 -l 0 raw 0x00 0x01 2>&1"
```

**Comment by CengSin** [comment]
`return with rc=2, output was: option -p not recognized`

**Comment by CengSin** [comment]
and i use the port `623` , output is same

**Comment by CengSin** [comment]
i use `ipmitool -I lanplus -H 172.16.19.111 -U root -P calvin chassis power status` can have the power status by windows `cmd`

**Comment by hthiery** [comment]
Seems there is an issue with your installed ipmitool. What version do you use?

The -p option ist not known.

**Comment by hthiery** [comment]
We never used it under windows before. Can you please give the output of ipmitool -h

**Comment by CengSin** [comment]
I use reboot to solve the output, now the output is :
```python
IPMI Request [<pyipmi.msgs.chassis.GetChassisStatusReq object at 0x000000000A15D9B0>]
Running ipmitool "ipmitool -I lanplus -H 172.16.19.111 -p 623 -U "root" -P "calvin" -b 0 -l 0 raw 0x00 0x01 2>&1"
<pyipmi.chassis.ChassisStatus object at 0x000000000A15D9B0>
return with rc=0, output was:
 01 10 40 54

IPMI Response [<pyipmi.msgs.chassis.GetChassisStatusRsp object at 0x000000000A15DAC8>])
```

how can i to get the `Chassis Power is on`

**Comment by CengSin** [comment]
thx , Thank you for spending an afternoon with me to solve this problem. the last problem i can solve, very thanks
