### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by paulbarker-ca** [kontron/python-ipmi#4]
Hi,

I'm looking at using python-ipmi in some software development and it would be good to be using a released version rather than just the HEAD of the master branch. Do you have any plans to make a release with a version number?

Thanks,
Paul

**Comment by hthiery** [comment]
Hi,

you're right! This is something that has to be done. I will check this and try to get a release version soon.

Heiko

**Comment by paulbarker-ca** [comment]
Many thanks for the quick response!

**Comment by hthiery** [comment]
version 0.1.0 is released and now available
