### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by lbazan** [kontron/python-ipmi#53]
+ pytest-3.7 tests
================================================================ test session starts =================================================================
platform linux -- Python 3.7.2, pytest-3.6.4, py-1.5.4, pluggy-0.6.0
rootdir: /home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1, inifile:
plugins: cov-2.5.1
collected 242 items                                                                                                                                  

tests/test_bmc.py ...                                                                                                                          [  1%]
tests/test_chassis.py .                                                                                                                        [  1%]
tests/test_errors.py ........                                                                                                                  [  4%]
tests/test_fields.py ...                                                                                                                       [  6%]
tests/test_fru.py ..FFF                                                                                                                        [  8%]
tests/test_helper.py .                                                                                                                         [  8%]
tests/test_hpm.py .......F                                                                                                                     [ 11%]
tests/test_ipmi.py .........                                                                                                                   [ 15%]
tests/test_picmg.py .....                                                                                                                      [ 17%]
tests/test_sdr.py ................                                                                                                             [ 24%]
tests/test_sel.py ..                                                                                                                           [ 25%]
tests/test_sensor.py .                                                                                                                         [ 25%]
tests/test_utils.py ............                                                                                                               [ 30%]
tests/interfaces/test_ipmb.py ........                                                                                                         [ 33%]
tests/interfaces/test_ipmitool.py .............                                                                                                [ 39%]
tests/interfaces/test_rmcp.py ...............                                                                                                  [ 45%]
tests/msgs/test_bmc.py ........                                                                                                                [ 48%]
tests/msgs/test_chassis.py ....                                                                                                                [ 50%]
tests/msgs/test_device_messaging.py .............................                                                                              [ 62%]
tests/msgs/test_event.py ....                                                                                                                  [ 64%]
tests/msgs/test_fru.py ...............                                                                                                         [ 70%]
tests/msgs/test_hpm.py .....                                                                                                                   [ 72%]
tests/msgs/test_message.py ......                                                                                                              [ 74%]
tests/msgs/test_picmg.py .............                                                                                                         [ 80%]
tests/msgs/test_sdr.py ................                                                                                                        [ 86%]
tests/msgs/test_sel.py ....                                                                                                                    [ 88%]
tests/msgs/test_sensor.py ............................                                                                                         [100%]

====================================================================== FAILURES ======================================================================
____________________________________________________________ test_fru_inventory_from_file ____________________________________________________________

    def test_fru_inventory_from_file():
        path = os.path.dirname(os.path.abspath(__file__))
        fru_file = os.path.join(path, 'fru_bin/kontron_am4010.bin')
>       fru = get_fru_inventory_from_file(fru_file)

tests/test_fru.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin'

    def get_fru_inventory_from_file(filename):
        try:
            file = open(filename, "rb")
        except IOError:
            print('Error open file "%s"' % filename)
    
        ################################
        # get file size
>       file_size = os.stat(filename).st_size
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin'

pyipmi/fru.py:99: FileNotFoundError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
Error open file "/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin"
__________________________________________________________________ test_board_area ___________________________________________________________________

    def test_board_area():
        path = os.path.dirname(os.path.abspath(__file__))
        fru_file = os.path.join(path, 'fru_bin/kontron_am4010.bin')
>       fru = get_fru_inventory_from_file(fru_file)

tests/test_fru.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin'

    def get_fru_inventory_from_file(filename):
        try:
            file = open(filename, "rb")
        except IOError:
            print('Error open file "%s"' % filename)
    
        ################################
        # get file size
>       file_size = os.stat(filename).st_size
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin'

pyipmi/fru.py:99: FileNotFoundError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
Error open file "/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin"
_________________________________________________________________ test_product_area __________________________________________________________________

    def test_product_area():
        path = os.path.dirname(os.path.abspath(__file__))
        fru_file = os.path.join(path, 'fru_bin/kontron_am4010.bin')
>       fru = get_fru_inventory_from_file(fru_file)

tests/test_fru.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

filename = '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin'

    def get_fru_inventory_from_file(filename):
        try:
            file = open(filename, "rb")
        except IOError:
            print('Error open file "%s"' % filename)
    
        ################################
        # get file size
>       file_size = os.stat(filename).st_size
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin'

pyipmi/fru.py:99: FileNotFoundError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
Error open file "/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/fru_bin/kontron_am4010.bin"
_________________________________________________________________ test_upgrade_image _________________________________________________________________

    def test_upgrade_image():
        path = os.path.dirname(os.path.abspath(__file__))
        hpm_file = os.path.join(path, 'hpm_bin/firmware.hpm')
>       image = UpgradeImage(hpm_file)

tests/test_hpm.py:94: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyipmi/hpm.py:678: in __init__
    self._from_file(filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyipmi.hpm.UpgradeImage object at 0x7fd08d5f3358>, filename = '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/hpm_bin/firmware.hpm'

    def _from_file(self, filename):
    
        try:
            file = open(filename, "rb")
        except IOError:
            print('Error open file "%s"' % filename)
    
        ################################
        # get file size
>       file_size = os.stat(filename).st_size
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/hpm_bin/firmware.hpm'

pyipmi/hpm.py:699: FileNotFoundError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
Error open file "/home/lbazan/rpmbuild/BUILD/python-ipmi-0.4.1/tests/hpm_bin/firmware.hpm"
================================================================== warnings summary ==================================================================
tests/msgs/test_message.py::TestMessage
  cannot collect test class 'TestMessage' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================================================== 4 failed, 238 passed, 1 warnings in 3.69 seconds ==================================================
error: Bad exit status from /var/tmp/rpm-tmp.DMBEs1 (%check)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.DMBEs1 (%check)

**Comment by hthiery** [comment]
how did you execute the tests? when executing the test from the source directory this issue cannot be reproduced.

**Comment by lbazan** [comment]
thanks!
