### ISSUE TITLE
Writing documentation

### ISSUE THREAD

**Issue by FerencFarkasPhD** [kontron/python-ipmi#55]
Hi,

I am very glad that you made effort on putting this library together. I definitely would like to use it for gathering sensor and other info from the distance of our server designed by us . This feature would be useful for making predictive maintenance with machine learning in the future.

I am new to github, so I do not know how to contribute to this project (also my python knowledge is moderate only).

As a first step I want to contribute by writing a documentation for this library. I started writing in Word doc a few days ago, but I assume this is not the preferred format (maybe Jupyter Notebook?). While I am writing the doc I use mostly reverse engineering by reading your code (that is also a good exercise for knowing better python) and also with trial and error by using our servers for sending/receiving IPMI commands (I am also new to IPMI standard, so this is another area which I am learning).

Please, provide your feedback., what format shall be used for documenting the library. Meanwhile I attached what I did till now.
[pyipmi_doc.docx](https://github.com/kontron/python-ipmi/files/2919111/pyipmi_doc.docx)

Regards,
Ferenc

**Comment by mwalle** [comment]
Hi Ferenc,

Am 2019-03-01 11:55, schrieb Ferenc Farkas, PhD:
> Hi,
> 
> I am very glad that you made effort on putting this library together.
> I definitely would like to use it for gathering sensor and other info
> from the distance of our server designed by us . This feature would be
> useful for making predictive maintenance with machine learning in the
> future.
> 
> I am new to github, so I do not know how to contribute to this project
> (also my python knowledge is moderate only).
> 
> As a first step I want to contribute by writing a documentation for
> this library. I started writing in Word doc a few days ago, but I
> assume this is not the preferred format (maybe Jupyter Notebook?).
> While I am writing the doc I use mostly reverse engineering by reading
> your code (that is also a good exercise for knowing better python) and
> also with trial and error by using our servers for sending/receiving
> IPMI commands (I am also new to IPMI standard, so this is another area
> which I am learning).
> 
> Please, provide your feedback., what format shall be used for
> documenting the library. Meanwhile I attached what I did till now.
> pyipmi_doc.docx [1]

first let me thank to take initiative and try to write documentation for 
our project. Unfortunately, I wasn't yet able to read what you've done 
so far, as I have no windows here and I am to lazy to install 
libreoffice for now ;) So yes, the docx format is not ideal for 
documentation. Python documentation is usually done with Sphinx in 
restructured text format. See our python-aardvark for example 
https://pyaardvark.readthedocs.io/en/latest/. The sources for the 
documentation is within the repository: 
https://github.com/kontron/python-aardvark/tree/master/docs

-michael

**Comment by FerencFarkasPhD** [comment]
Ohh no! Another tool to learn. 🤕 

Attached the doc in pdf format. This is very first draft, but I would be happy if you provide some feedback if the direction is OK.
[pyipmi_doc.pdf](https://github.com/kontron/python-ipmi/files/2919523/pyipmi_doc.pdf)

BR/Ferenc

**Comment by hthiery** [comment]
Any documentation is welcome. But as Michael already mentioned we prefer the restructred text format. With this format we automatically can create the online documentation. Also other output formats are possible, like PDF.

**Comment by FerencFarkasPhD** [comment]
OK, done with Sphinx. Currently, I have the following files:
- conf.py (created with sphinx-quickstart)
- index.rst
- intro.rst (mainly the readme.rst what you have
- quick_start.rst (compiled from my earlier doc and your examples)
- ipm_cmd.rst (my earlier doc)

(I tried to use graphviz, but that is another tool and I could not succeed yet to make the right graph for routing example 2 from your code comment. The dot.exe works with Spinx, there is no problem with that.)

On my laptop the html looks nice. 🤥 

I have Git GUI installed on my computer (the command line version is also installed). What is the next step? How can I commit these files to this github?

BR/Ferenc

**Comment by hthiery** [comment]
Please follow this guidline: https://gist.github.com/MarcDiethelm/7303312

**Comment by FerencFarkasPhD** [comment]
OK, done. Pull request for 8 files.
I hope it will work for you (graphviz is also used). 
html on my laptop looks ok for graphics, as well.

I want to know that this is the channel of communication, because I have a lot of questions for you guys.

BR/Ferenc

**Comment by FerencFarkasPhD** [comment]
Because you only pulled the 8 files I dared to make a build from my fork:

https://python-ipmi.readthedocs.io/en/latest/index.html

Probably this is not the best way to do it, but I was eager to see the result (one graphviz does not show for some reason).

Any idea how to make this build more formally?

**Comment by hthiery** [comment]
No problem .. just checked the result and it looks good. This is something that was missed for a long time. Thanks again.

Did you manually build this documentation or was it done automatically from the git sources?

**Comment by hthiery** [comment]
For more detailed discussions you can send an email. Please check the commit messages there you will find the mail address (in the signed-off field).

**Comment by FerencFarkasPhD** [comment]
Mail sent. I think we can close this issue.

**Comment by hthiery** [comment]
thanks again for your work ... added mention in readme and add a badge
