### ISSUE TITLE
Readme should list supported python versions

### ISSUE THREAD

**Issue by paulbarker-ca** [kontron/python-ipmi#7]
'import pyipmi' works for my in python 2.7

It fails for me in python 3.4:
```
Traceback (most recent call last):
  File "src/hello.py", line 1, in <module>
    import pyipmi
  File "...\pyipmi\__init__.py", line 174
    except CompletionCodeError, e:
                              ^
SyntaxError: invalid syntax
```

Is python 3 supported? If not could you update the readme to indicate this so that it's clear to new users of this library.

Thanks!

**Comment by hthiery** [comment]
I added an indication in the README.
