### ISSUE TITLE
I get the error: No module named 'pyipmi.interfaces'

### ISSUE THREAD

**Issue by 0byt3** [kontron/python-ipmi#70]
I am running Ubuntu 18.04 in WSL if that matters.

I downloaded the python-ipmi tarball and ran setup.py to install python-ipmi.

**Comment by hthiery** [comment]
Do you install as normal user or as root?
What are you doing when the get the error?
As an alternative you could try to install via pip.

**Comment by 0byt3** [comment]
I figured out the issue. I was using sudo python setup.py install . I have python2 and 3 installed.

sudo python3 setup.py install did the trick.

**Comment by 0byt3** [comment]
I assumed that meant python2 wasn't supported.

**Comment by hthiery** [comment]
python2 should still work ..
https://travis-ci.org/kontron/python-ipmi/jobs/579765965
