### ISSUE TITLE
how to read /dev/ipmi0

### ISSUE THREAD

**Issue by mhf-ir** [kontron/python-ipmi#72]
I use install ipmi tools and it's availibe with command :

it's directed by kernel module:
```
modprobe ipmi_devintf
modprobe ipmi_si
```

```
root@myserver:~# ipmitool sel info
SEL Information
Version          : 1.5 (v1.5, v2 compliant)
Entries          : 20
Free Space       : 704 bytes 
Percent Used     : 31%
Last Add Time    : 06/10/2019 09:37:05
Last Del Time    : 01/13/2012 09:04:19
Overflow         : false
Supported Cmds   : 'Reserve' 
```

Hot to use python-ipmi, no network lan or etc ... just direct call to kernel ipmi on `/dev/ipmi0`

**Comment by hthiery** [comment]
Hi,

you should use the ipmitool backend with interface type `opeǹ`.

Take a look on https://github.com/kontron/python-ipmi/blob/master/pyipmi/interfaces/ipmitool.py#L228.

**Comment by hthiery** [comment]
closed due to missing feedback
