### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("build_libdoc requires the Robot Framework package.")? when using released 0.2.2 version

### ISSUE THREAD

**Issue by vikitech83** [kontron/python-ipmi#74]
Hi ,
I've been trying to install version 0.2.2 on centos with python3.6 and getting following error :

"
Collecting robotframework-ipmilibrary==0.2.2 (from -r requirements.txt (line 67))
  Downloading https://files.pythonhosted.org/packages/62/08/61f1cf31f50fa85089cc33408d92c6ad8e160c93c1a75d4a5ca0f53ac205/robotframework-ipmilibrary-0.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l_f7aqpw/robotframework-ipmilibrary/setup.py", line 49
        print "build_libdoc requires the Robot Framework package."
                                                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("build_libdoc requires the Robot Framework package.")?

"
isn't this version of library suppose to work on python3.6?

**Comment by hthiery** [comment]
Hi,

this is an error coming from robotframework-ipmilibrary and not python-ipmi.

But on robotframework-ipmilibrary this seems to fixed since quiet a while.
