### ISSUE TITLE
'ipmitool.py fru print 0 all' fails

### ISSUE THREAD

**Issue by paulbarker-ca** [kontron/python-ipmi#8]
With python-ipmi 0.1.0 I ran the following. "sipl_tm" is a custom interface I have added to communicate IPMI commands over a RS232 interface in TM (terminal mode) format.
```
python pyipmi\ipmitool.py -I sipl_tm fru print 0 all
```

Output:
```
<snip>
Multirecord Area:
Traceback (most recent call last):
  File "pyipmi\ipmitool.py", line 575, in <module>
    main()
  File "pyipmi\ipmitool.py", line 478, in main
    cmd(ipmi, args)
  File "pyipmi\ipmitool.py", line 223, in cmd_fru_print
    print '  %s' % record
  File "C:\Users\paul.barker\Git\ca-ipmi-test\lib\pyipmi\fru.py", line 261, in __str__
    return '%02x: %s' % (self.type,
AttributeError: FruPicmgRecord instance has no attribute 'type'
```

On line 261 of fru.py I can fix this issue by changing self.type to self.record_type_id and the resulting output makes sense. Is that the correct fix?

**Comment by hthiery** [comment]
Yes your're right ... this was an issue.

**Comment by paulbarker-ca** [comment]
Cheers and thanks again for the quick response!
