### ISSUE TITLE
Feature request. SOL option 

### ISSUE THREAD

**Issue by kumareshr** [kontron/python-ipmi#83]
Any in-progress or plan to include the native SOL feature with this module ? 

example : 
_`ipmitool -H <server>  -U <id> -P <pass> -I lanplus sol activate`_

OR 
This module already have this feature ? i unable find from wiki docs 

Thanks

**Comment by hthiery** [comment]
There is currently no plan to implement that. But PRs are welcome.

**Comment by luckyho** [comment]
This module already have this feature？

**Comment by luckyho** [comment]
is the feature already supported?

**Comment by hthiery** [comment]
> is the feature already supported?

No, feel free to provde support.
