### ISSUE TITLE
is there a way to use pyipmi to emulate IPMC

### ISSUE THREAD

**Issue by sulemanzp** [kontron/python-ipmi#85]
Hi, i would like to know if it is possible to use this library as a IPMC. So i can emulate IPMC and test it with this library as well for development for both IPMC and ChassisManager.

**Comment by hthiery** [comment]
Hi, currently this library only can be used for requesting data from IPMCs. The library could be extended to also support the functionality you are looking for. But there is no plan to do that.

**Comment by hthiery** [comment]
If you're interested in doing that PRs are welcome.

**Comment by mdevaev** [comment]
@sulemanzp see here: https://opendev.org/x/pyghmi

**Comment by sulemanzp** [comment]
Thank you for the messages. I will try to do that.

**Comment by hthiery** [comment]
For those who are interested. i have a rudimentary rmcp ipmi emulation available at [1]. BMC info and FRU data reading work. The RMCP interface is not fully implemented. If it is interesting for someone I would appreciate a feedback.

[1] https://github.com/hthiery/python-ipmi/tree/feature-emulation
