### ISSUE TITLE
PyPI version running behind (0.4.2 on PyPi, 0.5.0 on this repo)

### ISSUE THREAD

**Issue by nhjjreuter** [kontron/python-ipmi#94]
The current version of `pyipmi` on PyPI is 0.4.2, but since October 2020 there is a 0.5.0 release tag on this github repository. Will this version be released on PyPI, and if so, is there a time indication for this?

**Comment by hthiery** [comment]
just pushed tag 0.5.1 and deployed to pypi. Please give it a try and report issues.
