### ISSUE TITLE
Accessing Aardvark through Python IPMI module on windows fails

### ISSUE THREAD

**Issue by shvbalaji** [kontron/python-ipmi#95]
Hi Team,
I have installed Python-ipmi module with 2.7 version python, I am using Total Phase Aardvark and running an example to create IPMI Interface, so whenever run that I am getting an Pop up Error as **Error while Initializing Driver**.

But I could able to use Aardvark device though their Control phase application, it detects the Aardvark device and also able to use their Python API's to read the number of devices connected with port and serial number.

Could you anyone share details/comments on this issue? 
I would like to create a IPMI connection using python-ipmi module with aardvark device and do read/write with IPMI supported device.

**Comment by hthiery** [comment]
Did you properly install the python-ipmi package and what OS do you use? Could you check if you can access your aardvark with the python-aardvark command line tool?

**Comment by shvbalaji** [comment]
Hi, 
Thank you  for the response.
I am using windows 10 and I have verified the python-aardvark using their api's, able to print the port and devices details.
I believe I am getting error while it try to create the ipmi interface using aardvark with slave address and serial number, it is not able to find any devices and throws error as **unable to load usb driver**.

![image](https://user-images.githubusercontent.com/28678589/121037204-e2cab000-c774-11eb-8f4c-3e8a08faaa4b.png)

**Comment by hthiery** [comment]
What version of python-aardvark are you using? By the way. There is a newer python-ipmi version available on pypi.

**Comment by shvbalaji** [comment]
python-aardvark version is 0.7(pyaardvark-0.7-py2.7.egg-info, https://pypi.org/project/pyaardvark/).

Sure I will install the updated version of python-ipmi.

do I need to install this one as well? comments?
https://pypi.org/project/aardvark-py/#files

**Comment by hthiery** [comment]
aardvark-py from total phase is not needed.

**Comment by shvbalaji** [comment]
Ok, Thanks for the update. Any idea what might be the reason for this issue. I am using Total phase Aardvark i2c adapter for the testing.

**Comment by hthiery** [comment]
Currently I have no idea. We do not have a setup under windows. 

Did you check if you can do a scan with the cli tool from python-aardvark:

```
# python cli_tool.py scan
Device #0: 2237-473375
```

So it might be a problem under windows. Are you able to test it also under linux?

**Comment by shvbalaji** [comment]
I haven't tried with Linux machine, I get the same error **unable to load usb error** for cli_tool as well.

**Comment by hthiery** [comment]
Did you try to run with admin privileges under windows?

Balaji Sivakumar ***@***.***> schrieb am Mi., 9. Juni 2021,
17:22:

**Comment by hthiery** [comment]
any news on that?

**Comment by shvbalaji** [comment]
I haven't tried with the Linux machine, Still i get the same error in windows Machine.
I started building an IPMB message and planning to use the Aardvark Api's directly.

**Comment by hthiery** [comment]
I just can confirm this issue. There seems to change something in the aardvark API from totalphase.

**Comment by shvbalaji** [comment]
Thanks for confirming. Any plans to fix this issue?

**Comment by hthiery** [comment]
Can you confirm that you are using v3.0.0 of the aardvark windows usb driver? And is it possible that you test v2.16 once?

**Comment by shvbalaji** [comment]
Yes I am using V3.0.0 of aardvark windows usb driver. I will try the v2.16 and update.

**Comment by shvbalaji** [comment]
Update:
After Installing Aardvark usb Version2.16, I am able to create the IPMI connection using Aardvark interface. Also able to get the device id, Raw commands etc through library.

**Comment by hthiery** [comment]
thank you for the feedback .. I will close this issue since it is more related to the python-aardvark library (kontron/python-aardvark#23)
