### ISSUE TITLE
read_fru_data function problem

### ISSUE THREAD

**Issue by mgdsxhy** [kontron/python-ipmi#96]
env: 
python 3.7.8
python-ipmi 0.5.1

I want to get the following information through pyipmi
![image](https://user-images.githubusercontent.com/6211830/121454674-d3966d00-c9d5-11eb-8cdc-7e0050829651.png)
I tried read_fru_data() function, but get the following
![image](https://user-images.githubusercontent.com/6211830/121454859-21ab7080-c9d6-11eb-9c3e-efd6e3cc9fca.png)
How to return a JSON or object object?（Why not return a JSON or object）
Is there any other way?

**Comment by hthiery** [comment]
Hi, try to use get_fru_inventory(). That returns a FruInventory object. Feel free to add a method to return the data as json. Take a look at https://github.com/kontron/python-ipmi/blob/master/pyipmi/ipmitool.py#L210 as an example.

**Comment by hthiery** [comment]
was your issue solved?
